# Generated by Django 6.0.7 on 2026-08-03 20:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('COCINA', 'Cocinero / Ayudante de Cocina'), ('MESERO', 'Mesero / Garzón'), ('CAJERO', 'Cajero'), ('BARMAN', 'Barman'), ('LIMPIEZA', 'Mantenimiento y Limpieza'), ('ADMINISTRACION', 'Administración / Gerencia')], default='MESERO', max_length=50)),
                ('cedula_carnet', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, default=0.0, help_text='Tarifa en Córdobas/USD por hora trabajada', max_digits=10)),
                ('qr_code_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR_EMPLEADO', 'Crear Empleado'), ('EDITAR_EMPLEADO', 'Editar Empleado'), ('ELIMINAR_EMPLEADO', 'Eliminar Empleado'), ('REGISTRO_MANUAL', 'Registro Manual de Asistencia'), ('EXPORTAR_NOMINA', 'Exportar Nómina / Reporte Excel')], max_length=50)),
                ('descripcion', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('ENTRADA', '🟢 Entrada (Inicio de Jornada)'), ('SALIDA_QUEBRADA', '🟡 Salida a Horario Quebrado (Pausa)'), ('ENTRADA_QUEBRADA', '🔵 Entrada de Horario Quebrado (Retorno)'), ('SALIDA_DEFINITIVA', '🔴 Salida Definitiva (Fin de Jornada)')], max_length=30)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto_verificacion', models.ImageField(blank=True, null=True, upload_to='asistencia_fotos/')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='asistencia.empleado')),
            ],
            options={
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
    ]
