# Generated by Django 6.0.7 on 2026-08-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_empleado_qr_code_token_alertaasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo_turno',
            field=models.CharField(choices=[('CORRIDO', 'Horario Corrido'), ('QUEBRADO', 'Horario Quebrado')], default='CORRIDO', max_length=20),
        ),
    ]
