# Generated by Django 6.0.7 on 2026-09-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_empleado_tipo_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='horas_pendientes',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Horas debidas acumuladas del período mensual vigente', max_digits=8),
        ),
        migrations.AddField(
            model_name='empleado',
            name='periodo_horas_pendientes',
            field=models.DateField(blank=True, help_text='Primer día del mes al que corresponde horas_pendientes (se reinicia al cambiar de mes)', null=True),
        ),
        migrations.AlterField(
            model_name='alertaasistencia',
            name='tipo',
            field=models.CharField(choices=[('TARDANZA', 'Tardanza'), ('SALIDA_ANTICIPADA', 'Salida Anticipada'), ('MARCACION_SOSPECHOSA', 'Marcación Sospechosa'), ('SEGUNDA_AUSENCIA', 'Segunda Ausencia en la Semana'), ('REGISTRO_INCOMPLETO', 'Registro Incompleto — Falta Salida')], max_length=30),
        ),
    ]
