# Generated by Django 6.0.7 on 2026-09-01 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_empleado_horas_pendientes_nuevas_alertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaasistencia',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='asistencia.empleado'),
        ),
        migrations.AlterField(
            model_name='alertaasistencia',
            name='tipo',
            field=models.CharField(choices=[('TARDANZA', 'Tardanza'), ('SALIDA_ANTICIPADA', 'Salida Anticipada'), ('MARCACION_SOSPECHOSA', 'Marcación Sospechosa'), ('SEGUNDA_AUSENCIA', 'Segunda Ausencia en la Semana'), ('REGISTRO_INCOMPLETO', 'Registro Incompleto — Falta Salida'), ('MANTENIMIENTO', 'Recordatorio de Mantenimiento Semestral')], max_length=30),
        ),
    ]
