# Generated by Django 6.0.7 on 2026-09-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_alerta_mantenimiento_semestral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('JEFE_COCINA', 'Jefe de Cocina'), ('COCINERO', 'Cocinero'), ('ASISTENTE_COCINA', 'Asistente de Cocina'), ('ATENCION_CLIENTE', 'Atención al Cliente'), ('BARRA', 'Barra'), ('LIMPIEZA', 'Limpieza'), ('LAVANDERIA', 'Lavandería'), ('ADMINISTRACION', 'Administración'), ('ASISTENTE_ADMON', 'Asistente de Administración')], default='ATENCION_CLIENTE', max_length=50),
        ),
    ]
