# Generated by Django 6.0.7 on 2026-09-02 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_cargos_oficiales_bodegon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('VACACIONES_PAGADAS', 'Vacaciones Pagadas'), ('INCAPACIDAD_MEDICA', 'Incapacidad Médica'), ('PERMISO_AUTORIZADO', 'Permiso Autorizado')], default='VACACIONES', max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='asistencia.empleado')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
