# Generated by Django 6.0.7 on 2026-09-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_permisos_ausencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='foto_base64',
            field=models.TextField(blank=True, help_text='Fotografía en Base64 persistente en Supabase', null=True),
        ),
    ]
