# Generated by Django 6.0.7 on 2026-09-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_alter_alertaasistencia_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisoausencia',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
