# Generated by Django 6.0.7 on 2026-09-04 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0011_permisoausencia_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensacionHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compensacion', models.DateField(help_text='Fecha en que el trabajador generó las horas extra')),
                ('horas_trabajadas_hoy', models.DecimalField(decimal_places=2, default=0.0, help_text='Total horas trabajadas en el día de la compensación', max_digits=5)),
                ('horas_extra_generadas', models.DecimalField(decimal_places=2, default=0.0, help_text='Exceso sobre 8h', max_digits=5)),
                ('horas_deducidas', models.DecimalField(decimal_places=2, default=0.0, help_text='Total horas extra usadas para saldar deuda', max_digits=5)),
                ('deuda_previa', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('saldo_restante', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('remanente_extra', models.DecimalField(decimal_places=2, default=0.0, help_text='Horas extra enviadas a aprobación tras saldar deuda', max_digits=5)),
                ('desglose', models.JSONField(blank=True, default=list, help_text='Detalle individualizado de cada día adeudado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensaciones_horas', to='asistencia.empleado')),
            ],
            options={
                'ordering': ['-fecha_compensacion', '-created_at'],
            },
        ),
    ]
