# Generated by Django on 2026-09-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0012_compensacionhoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dias_vacaciones_acumuladas',
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                help_text='Total días de vacaciones acumulados por ley (+2.5 días/mes o saldo inicial)',
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ultimo_corte_vacaciones',
            field=models.DateField(
                blank=True,
                help_text='Fecha del último mes acreditado (+2.5 días)',
                null=True,
            ),
        ),
    ]
