# Generated by Django 6.0.7 on 2026-09-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0013_empleado_vacaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dias_vacaciones_acumuladas',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total días de vacaciones acumulados por ley (+2.5 días/mes o acumulado diario continuo)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ultimo_corte_vacaciones',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual se han acreditado las vacaciones (corte diario/mensual)', null=True),
        ),
    ]
