# Generated by Django 6.0.7 on 2026-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0014_alter_empleado_dias_vacaciones_acumuladas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaasistencia',
            name='tipo',
            field=models.CharField(choices=[('TARDANZA', 'Tardanza'), ('SALIDA_ANTICIPADA', 'Salida Anticipada'), ('MARCACION_SOSPECHOSA', 'Marcación Sospechosa'), ('SEGUNDA_AUSENCIA', 'Segunda Ausencia en la Semana'), ('REGISTRO_INCOMPLETO', 'Registro Incompleto — Falta Salida'), ('MANTENIMIENTO', 'Recordatorio de Mantenimiento Semestral'), ('COMPENSACION_HORAS', 'Compensación de Horas (Bolsa de Horas)'), ('SANCION_DISCIPLINARIA', 'Sanción y Amonestación Disciplinaria')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bitacoraaccion',
            name='accion',
            field=models.CharField(choices=[('CREAR_EMPLEADO', 'Crear Empleado'), ('EDITAR_EMPLEADO', 'Editar Empleado'), ('ELIMINAR_EMPLEADO', 'Eliminar Empleado'), ('REGISTRO_MANUAL', 'Registro Manual de Asistencia'), ('EXPORTAR_NOMINA', 'Exportar Nómina / Reporte Excel'), ('SANCION_DISCIPLINARIA', 'Sanción Disciplinaria')], max_length=50),
        ),
    ]
