# Generated by Django 6.0.7 on 2026-09-15 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0015_alter_alertaasistencia_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraaccion',
            name='accion',
            field=models.CharField(choices=[('CREAR_EMPLEADO', 'Crear Empleado'), ('EDITAR_EMPLEADO', 'Editar Empleado'), ('ELIMINAR_EMPLEADO', 'Eliminar Empleado'), ('REGISTRO_MANUAL', 'Registro Manual de Asistencia'), ('EXPORTAR_NOMINA', 'Exportar Nómina / Reporte Excel'), ('SANCION_DISCIPLINARIA', 'Sanción Disciplinaria'), ('LIQUIDAR_FERIADO', 'Liquidación de Feriado')], max_length=50),
        ),
        migrations.CreateModel(
            name='CompensacionFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_feriado', models.DateField(help_text='Fecha del día feriado laborado')),
                ('nombre_feriado', models.CharField(blank=True, default='', max_length=150)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('dias_compensatorios_totales', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Liquidar'), ('DINERO', 'Pagado en Dinero'), ('VACACIONES', 'Acreditado a Vacaciones'), ('MIXTO', 'Pago Mixto (Dinero y Vacaciones)')], default='PENDIENTE', max_length=20)),
                ('dias_pagados_dinero', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('dias_acreditados_vacaciones', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('fecha_liquidacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensaciones_feriados', to='asistencia.empleado')),
            ],
            options={
                'ordering': ['-fecha_feriado', '-created_at'],
                'unique_together': {('empleado', 'fecha_feriado')},
            },
        ),
    ]
