# Generated by Django 6.0.7 on 2026-09-16 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0016_alter_bitacoraaccion_accion_compensacionferiado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraaccion',
            name='accion',
            field=models.CharField(choices=[('CREAR_EMPLEADO', 'Crear Empleado'), ('EDITAR_EMPLEADO', 'Editar Empleado'), ('ELIMINAR_EMPLEADO', 'Eliminar Empleado'), ('REGISTRO_MANUAL', 'Registro Manual de Asistencia'), ('EXPORTAR_NOMINA', 'Exportar Nómina / Reporte Excel'), ('SANCION_DISCIPLINARIA', 'Sanción Disciplinaria'), ('LIQUIDAR_FERIADO', 'Liquidación de Feriado'), ('PAGO_VACACIONES', 'Pago de Vacaciones en Dinero'), ('ACREDITAR_FERIADO_VACACIONES', 'Acreditación de Feriado a Vacaciones'), ('ACREDITAR_SEPTIMO_DIA_VACACIONES', 'Acreditación de Día Libre a Vacaciones')], max_length=50),
        ),
        migrations.CreateModel(
            name='PagoVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate, help_text='Fecha de emisión del pago')),
                ('dias_pagados', models.DecimalField(decimal_places=1, help_text='Cantidad de días de vacaciones liquidados en dinero', max_digits=5)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto en Córdobas acordado/pagado manualmente por Administración', max_digits=10)),
                ('dias_saldo_anterior', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('dias_saldo_nuevo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('motivo', models.CharField(blank=True, default='Pago de Vacaciones en Dinero', max_length=255)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('numero_recibo', models.CharField(help_text='Número correlativo de boleta oficial (ej. BVP-2026-0001)', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_vacaciones', to='asistencia.empleado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
    ]
