# Generated by Django 6.0.7 on 2026-09-18 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0017_alter_bitacoraaccion_accion_pagovacaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionhorasextra',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='autorizacionhorasextra',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autorizacionhorasextra',
            name='metodo_pago',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='autorizacionhorasextra',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='autorizacionhorasextra',
            name='numero_recibo_pago',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='PagoHorasExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate, help_text='Fecha de emisión del pago')),
                ('total_horas_pagadas', models.DecimalField(decimal_places=2, help_text='Horas extra efectivas liquidadas', max_digits=6)),
                ('tarifa_hora_aplicada', models.DecimalField(decimal_places=2, default=0.0, help_text='Tarifa por hora extra (C$) aplicada', max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total pagado en Córdobas (C$)', max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('NOMINA_QUINCENAL', 'En Nómina Quincenal')], default='EFECTIVO', max_length=30)),
                ('numero_recibo', models.CharField(help_text='Número correlativo de boleta oficial (ej. RPHE-2026-0001)', max_length=50, unique=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('detalles_fechas', models.JSONField(blank=True, default=list, help_text='Detalle de fechas y horas pagadas en este recibo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_horas_extra', to='asistencia.empleado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='autorizacionhorasextra',
            name='pago_horas_extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_extra_asociadas', to='asistencia.pagohorasextra'),
        ),
    ]
