# Generated by Django 6.0.7 on 2026-09-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0018_autorizacionhorasextra_estado_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraaccion',
            name='accion',
            field=models.CharField(choices=[('CREAR_EMPLEADO', 'Crear Empleado'), ('EDITAR_EMPLEADO', 'Editar Empleado'), ('ELIMINAR_EMPLEADO', 'Eliminar Empleado'), ('REGISTRO_MANUAL', 'Registro Manual de Asistencia'), ('EXPORTAR_NOMINA', 'Exportar Nómina / Reporte Excel'), ('SANCION_DISCIPLINARIA', 'Sanción Disciplinaria'), ('LIQUIDAR_FERIADO', 'Liquidación de Feriado'), ('PAGO_VACACIONES', 'Pago de Vacaciones en Dinero'), ('PAGO_HORAS_EXTRA', 'Pago de Horas Extra'), ('ACREDITAR_FERIADO_VACACIONES', 'Acreditación de Feriado a Vacaciones'), ('ACREDITAR_SEPTIMO_DIA_VACACIONES', 'Acreditación de Día Libre a Vacaciones')], max_length=50),
        ),
    ]
