# Generated by Django 6.0.7 on 2026-10-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0019_alter_bitacoraaccion_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaasistencia',
            name='tipo',
            field=models.CharField(choices=[('TARDANZA', 'Tardanza'), ('SALIDA_ANTICIPADA', 'Salida Anticipada'), ('MARCACION_SOSPECHOSA', 'Marcación Sospechosa'), ('SEGUNDA_AUSENCIA', 'Segunda Ausencia en la Semana'), ('REGISTRO_INCOMPLETO', 'Registro Incompleto — Falta Salida'), ('MANTENIMIENTO', 'Recordatorio de Mantenimiento Semestral'), ('COMPENSACION_HORAS', 'Compensación de Horas (Bolsa de Horas)'), ('SANCION_DISCIPLINARIA', 'Sanción y Amonestación Disciplinaria'), ('INASISTENCIA', 'Inasistencia / Falta a Laborar')], max_length=30),
        ),
    ]
